name: life_butler_desktop
description: Life Butler AI Desktop Application
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  core:
    path: ../../packages/core
  data:
    path: ../../packages/data
  providers_llm:
    path: ../../packages/providers_llm

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Storage
  shared_preferences: ^2.2.2

  # Navigation
  go_router: ^13.2.4

  # UI
  flutter_markdown: ^0.6.20+1

  # File handling
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  image_picker: ^1.0.7

  # Environment
  flutter_dotenv: ^5.1.0

  # Utils
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - .env
